version: '3'
services:
  app:
    image: web
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./pages:/usr/src/app/pages
      - ./public:/usr/src/app/public
      - ./styles:/usr/src/app/styles
      - ./components:/usr/src/app/components